---
- name: install puppet rpm from remote repo
  hosts: localhost:nodes
  gather_facts: no
  tasks:
    - name: install puppet package
      yum:
        name: https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
        state: present

- name: set puppetserver
  hosts: localhost
  gather_facts: no
  tasks:
    - name: install puppet server
      yum:
        name: puppetserver
        state: present
    - name: edit puppet.conf
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          [agent]
          certname = {{ inventory_hostname }}
          environment = production
          server = master
          runinterval = 600
    - name: make environment dirs
      file:
        path: /etc/puppetlabs/code/environments/node/manifests
        state: directory
    - name: start puppetserver
      service:
        name: puppetserver
        state: started

- name: set puppet
  hosts: nodes
  gather_facts: no
  tasks:
    - name: install puppet
      yum:
        name: puppet
        state: present
    - name: edit puppet.conf
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          certname = {{ inventory_hostname }}
          environment = node
          server = master
          runinterval = 600
