---
- name: install puppet rpm from remote repo
  hosts: localhost:nodes
  gather_facts: no
  tasks:
    - name: install puppet package
      yum:
        name: https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
        state: present

- name: set puppetserver
  hosts: localhost
  gather_facts: no
  tasks:
    - name: install puppet server
      yum:
        name: puppetserver
        state: present

- name: set puppet
  hosts: nodes
  gather_facts: no
  tasks:
    - name: install puppet
      yum:
        name: puppet
        state: present
