---
- name: install puppet rpm from remote repo
  hosts: all
  gather_facts: no
  tasks:
    - name: install puppet package
      yum:
        name: https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
        state: present

- name: set puppet master
  hosts: master
  gather_facts: no
  tasks:
    - name: install puppetserver for master
      yum:
        name: puppetserver
        state: present
    - name: edit puppet.conf
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          [main]
          certname = {{ inventory_hostname }}
          environment = production
          server = master.puppet.test
          runinterval = 600
    - name: create autosign.conf file
      file:
        path: /etc/puppetlabs/puppet/autosign.conf
        state: touch
    - name: edit autosign.conf
      blockinfile:
        path: /etc/puppetlabs/puppet/autosign.conf
        block: |
          *.puppet.test
    - name: make environment dirs
      file:
        path: /etc/puppetlabs/code/environments/node/manifests
        state: directory
    - name: start puppetserver
      service:
        name: puppetserver
        state: started

- name: set puppet agents
  hosts: nodes
  gather_facts: no
  tasks:
    - name: install puppet on agent
      yum:
        name: puppet-agent
        state: present
    - name: edit puppet.conf
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          [main]
          certname = {{ inventory_hostname }}
          environment = node
          server = master.puppet.test
          runinterval = 600
